[profile.default]
src = 'packages/contracts/src'
test = 'packages/contracts/tests'
libs = ['packages/contracts/lib']
out = 'packages/contracts/out'
optimizer = true
solc_version = '0.8.17'

[fmt]
tab_width = 2