[profile.default]
src = 'src'
test = 'tests'
libs = ['lib']
out = 'out'
optimizer = true
solc_version = '0.8.28'
evm_version = 'cancun'
eth_rpc_url = 'https://rpc.gnosischain.com'

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
gnosis = "${GNOSIS_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
base = "${BASE_RPC_URL}"

[fmt]
tab_width = 2